#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Enter,
    Esc,
    Backspace,
    Tab,
    Space,
    LeftShift,
    RightShift,
    LeftCtrl,
    RightCtrl,
    LeftAlt,
    RightAlt,
    Up,
    Down,
    Left,
    Right,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    Semicolon,
    Apostrophe,
    Grave,
    Backslash,
    NonUsBackslash,
    Comma,
    Dot,
    Slash,
    CapsLock,
    Insert,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,
    LeftMeta,
    RightMeta,
    Mute,
    VolumeDown,
    VolumeUp,
    PlayPause,
    Unknown(u16),
}

impl Key {
    pub fn to_code(self) -> u16 {
        match self {
            Key::Unknown(code) => code,
            Key::A => 30,
            Key::B => 48,
            Key::C => 46,
            Key::D => 32,
            Key::E => 18,
            Key::F => 33,
            Key::G => 34,
            Key::H => 35,
            Key::I => 23,
            Key::J => 36,
            Key::K => 37,
            Key::L => 38,
            Key::M => 50,
            Key::N => 49,
            Key::O => 24,
            Key::P => 25,
            Key::Q => 16,
            Key::R => 19,
            Key::S => 31,
            Key::T => 20,
            Key::U => 22,
            Key::V => 47,
            Key::W => 17,
            Key::X => 45,
            Key::Y => 21,
            Key::Z => 44,
            Key::Enter => 28,
            Key::Esc => 1,
            Key::Backspace => 14,
            Key::Tab => 15,
            Key::Space => 57,
            Key::LeftShift => 42,
            Key::RightShift => 54,
            Key::LeftCtrl => 29,
            Key::RightCtrl => 97,
            Key::LeftAlt => 56,
            Key::RightAlt => 100,
            Key::Up => 103,
            Key::Down => 108,
            Key::Left => 105,
            Key::Right => 106,
            Key::F1 => 59,
            Key::F2 => 60,
            Key::F3 => 61,
            Key::F4 => 62,
            Key::F5 => 63,
            Key::F6 => 64,
            Key::F7 => 65,
            Key::F8 => 66,
            Key::F9 => 67,
            Key::F10 => 68,
            Key::F11 => 87,
            Key::F12 => 88,
            Key::Num1 => 2,
            Key::Num2 => 3,
            Key::Num3 => 4,
            Key::Num4 => 5,
            Key::Num5 => 6,
            Key::Num6 => 7,
            Key::Num7 => 8,
            Key::Num8 => 9,
            Key::Num9 => 10,
            Key::Num0 => 11,
            Key::Minus => 12,
            Key::Equal => 13,
            Key::LeftBracket => 26,
            Key::RightBracket => 27,
            Key::Semicolon => 39,
            Key::Apostrophe => 40,
            Key::Grave => 41,
            Key::Backslash => 43,
            Key::NonUsBackslash => 86,
            Key::Comma => 51,
            Key::Dot => 52,
            Key::Slash => 53,
            Key::CapsLock => 58,
            Key::Insert => 110,
            Key::Delete => 111,
            Key::Home => 102,
            Key::End => 107,
            Key::PageUp => 104,
            Key::PageDown => 109,
            Key::LeftMeta => 125,
            Key::RightMeta => 126,
            Key::Mute => 113,
            Key::VolumeDown => 114,
            Key::VolumeUp => 115,
            Key::PlayPause => 164,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Side,
    Extra,
    Unknown(u16),
}

pub fn key_from_evdev(code: u16) -> Key {
    match code {
        30 => Key::A,
        48 => Key::B,
        46 => Key::C,
        32 => Key::D,
        18 => Key::E,
        33 => Key::F,
        34 => Key::G,
        35 => Key::H,
        23 => Key::I,
        36 => Key::J,
        37 => Key::K,
        38 => Key::L,
        50 => Key::M,
        49 => Key::N,
        24 => Key::O,
        25 => Key::P,
        16 => Key::Q,
        19 => Key::R,
        31 => Key::S,
        20 => Key::T,
        22 => Key::U,
        47 => Key::V,
        17 => Key::W,
        45 => Key::X,
        21 => Key::Y,
        44 => Key::Z,
        28 => Key::Enter,
        1 => Key::Esc,
        14 => Key::Backspace,
        15 => Key::Tab,
        57 => Key::Space,
        42 => Key::LeftShift,
        54 => Key::RightShift,
        29 => Key::LeftCtrl,
        97 => Key::RightCtrl,
        56 => Key::LeftAlt,
        100 => Key::RightAlt,
        103 => Key::Up,
        108 => Key::Down,
        105 => Key::Left,
        106 => Key::Right,
        59 => Key::F1,
        60 => Key::F2,
        61 => Key::F3,
        62 => Key::F4,
        63 => Key::F5,
        64 => Key::F6,
        65 => Key::F7,
        66 => Key::F8,
        67 => Key::F9,
        68 => Key::F10,
        87 => Key::F11,
        88 => Key::F12,
        2 => Key::Num1,
        3 => Key::Num2,
        4 => Key::Num3,
        5 => Key::Num4,
        6 => Key::Num5,
        7 => Key::Num6,
        8 => Key::Num7,
        9 => Key::Num8,
        10 => Key::Num9,
        11 => Key::Num0,
        12 => Key::Minus,
        13 => Key::Equal,
        26 => Key::LeftBracket,
        27 => Key::RightBracket,
        39 => Key::Semicolon,
        40 => Key::Apostrophe,
        41 => Key::Grave,
        43 => Key::Backslash,
        86 => Key::NonUsBackslash,
        51 => Key::Comma,
        52 => Key::Dot,
        53 => Key::Slash,
        58 => Key::CapsLock,
        110 => Key::Insert,
        111 => Key::Delete,
        102 => Key::Home,
        107 => Key::End,
        104 => Key::PageUp,
        109 => Key::PageDown,
        125 => Key::LeftMeta,
        126 => Key::RightMeta,
        113 => Key::Mute,
        114 => Key::VolumeDown,
        115 => Key::VolumeUp,
        164 => Key::PlayPause,
        _ => Key::Unknown(code),
    }
}

pub fn mouse_button_from_evdev(code: u16) -> MouseButton {
    match code {
        0x110 => MouseButton::Left,
        0x111 => MouseButton::Right,
        0x112 => MouseButton::Middle,
        0x113 => MouseButton::Side,
        0x114 => MouseButton::Extra,
        _ => MouseButton::Unknown(code),
    }
}
